package.json

Bumped dep on stripes-kint-components to v1.1.1

chore: kint-components v1.1.1

---

src/components/PublicationRequestFormSections/RequestInfoForm/RequestInfoForm.js

Added requied validator to request date and request status fields
UIOA-34, UIOA-36

feat: Added validators

---

src/routes/PublicationRequestCreateRoute.js
translations/ui-oa/en_US.json

Added a success callout that displays when a publication request is successfully saved

feat: Added Publication Request Success Callout

---

src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray.js

Bring frontend in line with funding domain model
UIOA-44

fix: Fundings

---

package.json

eslint-config-stripes update from 5.2.0 to 6.0.0

fix: eslint-config-stripes update

---

translations/ui-oa/en.json

Added translation for selected journal "Selected journal" UIOA-58

fix: Added translation for selectedJournal

---

src/components/PublicationRequestSections/Funding/Funding.js
src/components/views/PublicationRequest/PublicationRequest.js

Funder now displayed in edit/view with "Funder" and "Aspect Funded"
UIOA-35

feat: Added funder in publication request edit/view

---

src/components/views/PublicationRequestForm/PublicationRequestForm.js
translations/ui-oa/en.json

Added OA icon and close form option to both create and edit publication request pages 
UIOA-39

feat: Applied UX guidelines to create/edit pages

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal.js
src/components/PublicationRequestSections/JournalDetails.js
src/util/journalUtils.js
translations/ui-oa/en.json

Removed duplicates from journal typedown by using work rather than title instances, the typedown card now also shows correct associated print and electronic ISSNs
UIOA-51

feat: Use work rather than title instance in journal lookup dropdown

---

package.json
src/util/useOARefdata.js

Bumped Stripes-Kint-Components to 1.7.0, tweaked import
UIOA-63, UIOA-56

chore: Stripes-Kint-Components

---

src/components/PartySections/PartyInfo/PartyInfo.js
src/routes/PartiesRoute.js
translations/ui-oa/en.json

Added ORCID iD to search and filter results columns
UIOA-67

feat: Added ORCID iD to parties view

---

.eslintrc
src/components/CorrespondenceFormSections/CorrespondenceInfoForm/CorrespondenceInfoForm.js
src/components/PartyFormSections/PartyInfoForm/Index.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js
src/components/PartyModal/PartyModal.js
src/components/PartyModal/index.js
src/components/PartySections/index.js
src/components/PublicationRequestFormSections/CorrespondingAuthorForm/CorrespondingAuthorForm.js
src/components/PublicationRequestFormSections/RequestContactForm/RequestContactForm.js
src/components/views/Party/Party.js
src/components/views/PartyForm/PartyForm.js
src/components/views/PartyForm/index.js
src/index.js
src/routes/PartyEditRoute.js
src/routes/index.js
src/settings/index.js
src/util/urls.js
translations/ui-oa/en.json

Added the ability to create new corresponding author / request contact to add to an open access publication request from within the publication request create/edit
UIOA-26

feat: Create party in publication request create/edit

---

src/components/SearchAndFilter/OAFilterHeaderComponent/OAFilterHeaderComponent.js
src/components/views/Journal/Journal.js
src/components/views/Journal/index.js
src/components/views/Party/Party.js
src/components/views/PartyForm/PartyForm.js
src/index.js
src/routes/JournalsRoute.js
src/routes/PartiesRoute.js
src/routes/index.js
translations/ui-oa/en.json

Added search and filter component for journals, along with lookup and view components
UIOA-68

feat: Add search and filter for Journals

---

src/components/JournalSections/JournalInstances/JournalInstances.js
src/components/PartySections/PartyInfo/PartyInfo.js
src/components/PublicationRequestFormSections/FieldArrays/AffiliationFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/IdentifiersFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/OtherEmailFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/StreetAddressesFieldArray.js
src/components/PublicationRequestFormSections/RequestInfoForm/RequestInfoForm.js
src/components/PublicationRequestSections/Agreement/Agreement.js
src/components/PublicationRequestSections/PartyInfo.js
src/components/PublicationRequestSections/Publication/Publication.js
src/components/PublicationRequestSections/PublicationType/BookDetails.js
src/components/PublicationRequestSections/PublicationType/JournalDetails.js
src/components/PublicationRequestSections/RequestInfo/RequestInfo.js
src/components/views/CorrespondenceView/CorrespondenceView.js
src/routes/CorrespondenceViewRoute.js

refactor: Refactor components

---

src/components/PublicationRequestFormSections/LinkAgreementForm/LinkAgreementForm.js

Added option to delete linked agreement
UIOA-72

feat: Delete Linked Agreement

---

src/routes/CorrespondenceCreateRoute/CorrespondenceCreateRoute.js
src/routes/CorrespondenceCreateRoute/index.js
src/routes/CorrespondenceEditRoute/CorrespondenceEditRoute.js
src/routes/CorrespondenceEditRoute/index.js
src/routes/CorrespondenceViewRoute/CorrespondenceViewRoute.js
src/routes/CorrespondenceViewRoute/index.js
src/routes/JournalsRoute/JournalsRoute.js
src/routes/JournalsRoute/index.js
src/routes/PartiesRoute/PartiesRoute.js
src/routes/PartiesRoute/index.js
src/routes/PartyEditRoute/PartyEditRoute.js
src/routes/PartyEditRoute/index.js
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/routes/PublicationRequestCreateRoute/index.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js
src/routes/PublicationRequestEditRoute/index.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js
src/routes/PublicationRequestsRoute/index.js

Refactored routes files for ease of testing

refactor: Refactored Routes Files

---

src/components/PartySections/PartyInfo/PartyInfo.js
src/components/views/PublicationRequest/PublicationRequest.js
src/routes/PartiesRoute/PartiesRoute.js

Refactored PartyInfo in order to reduce duplicate code
Also general code tidy-up

refactor: PartyInfo Refactor

---

src/components/JournalFormSections/FieldArrays/InstancesFieldArray/InstancesFieldArray.js

Fixed instance subtype value from being saved as UUID to instead be the correct Electronic or print value

fix: Fixed subType Value

---

translations/ui-oa/en.json

Fixed the translation issue for callout when creating a new publication request
UIOA-37

fix: Publication request creation callout

---

src/components/PublicationRequestSections/Publication/Publication.test.js
test/helpers/translationsProperties.js

test: NoValue change

---

src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray/ExternalRequestIdFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray/ExternalRequestIdFieldArray.test.js
src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray/FundingFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray/FundingFieldArray.test.js
src/components/PublicationRequestFormSections/FieldArrays/IdentifiersFieldArray/IdentifiersFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/PublicationStatusFieldArray/PublicationStatusFieldArray.js

Funding field array now removes items when publication request is edited
Also refactored other field arrays for consistency
UIOA-44

fix: Funding information not removed when edited

---

package.json

Removed history dep due to stripesHarness refactor

chore: Removed history dependency

---

src/components/PublicationRequestSections/Charges/Charges.js
src/components/views/ChargeView/ChargeView.js

Various fixes to charges accordion and view pane

fix: Charges view fixes

---

src/components/PublicationRequestSections/Charges/Charges.js
translations/ui-oa/en.json
translations/ui-oa/en_US.json

Fixed currency conversion calculations and translations used in estimated prices column

fix: Charges MCL

---

src/components/JournalFormSections/FieldArrays/InstanceIdentifiersFieldArray/InstanceIdentifiersFieldArray.js
src/components/JournalFormSections/FieldArrays/InstancesFieldArray/InstancesFieldArray.js
src/components/JournalFormSections/JournalInfoForm/JournalInfoForm.js
src/components/Modals/JournalModal/JournalModal.css
src/components/Modals/JournalModal/JournalModal.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
translations/ui-oa/en.json

Made various improvements to the journal modal, including tool tips for instance and identifier removal, a submission animation and extension of title field
UIOA-90

feat: Journal Modal Improvements

---

src/components/views/ChargeView/ChargeView.js
src/components/views/Journal/Journal.js
src/components/views/Journal/Journal.test.js
src/components/views/Party/Party.js
src/components/views/Party/Party.test.js
src/components/views/PublicationRequest/PublicationRequest.js
src/components/views/PublicationRequest/PublicationRequest.test.js
src/routes/ChargeRoute/ChargeRoute.js

Made various tweaks to query props in routes

fix: Route tweaks

---

src/components/PartySections/RelatedRequests/RelatedRequests.js
src/components/PartySections/RelatedRequests/index.js
src/components/PartySections/index.js
src/components/views/Party/Party.js
src/components/views/Party/Party.test.js
translations/ui-oa/en.json

Added related requests accordion and MCL to party view pane
UIOA-92

feat: Related requests

---

src/components/PartySections/RelatedRequests/RelatedRequests.js
src/components/views/Party/Party.js
src/util/getSortedItems.js

Added functionality for user to sort related requests MCL fields
UIOA-92

feat: Related requests sort

---

package.json

Added stripes-acq-components dependancy

chore: Stripes-acq-components

---

src/components/PublicationRequestSections/Charges/Charges.js
src/components/views/ChargeView/ChargeView.js

Fixed currency display on charge/charges view

fix: Charge currency display

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.test.js

Currency field in charge create/edit now displays all supported currencies
UIOA-93

feat: Currency lookup

---

src/components/PartySections/PartyInfo/PartyInfo.js
src/components/PartySections/PartyInfo/PartyInfo.test.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js
translations/ui-oa/en.json

Reformatted party info to display as "Title Surname Firstname"
In request search and filter, requests can be searched for by corresponding author
UIOA-45, UIOA-95

feat: Party search/display

---

src/components/Modals/PartyModal/PartyModal.js
src/components/PartyFormSections/OtherEmailsFieldArray/OtherEmailsFieldArray.js
src/components/PartyFormSections/OtherEmailsFieldArray/index.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js
src/components/PartyFormSections/index.js
src/components/PartySections/PartyInfo/PartyInfo.js
src/components/PublicationRequestSections/CorrespondingAuthor/CorrespondingAuthor.js
src/components/PublicationRequestSections/CorrespondingAuthor/CorrespondingAuthor.test.js
src/components/PublicationRequestSections/RequestContact/RequestContact.js
src/components/views/PartyForm/PartyForm.js
src/components/views/PartyForm/PartyForm.test.js
translations/ui-oa/en.json

Added the ability for the user to add alternate email addresses through the party create/edit page
Party info display components also now correctly display these alternate email addresses
UIOA-42

feat: Other email addresses

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/components/ChargeSections/ChargeInfo/ChargeInfo.js
src/components/InvoiceSections/InvoiceInfo/InvoiceInfo.js
src/components/Modals/InvoiceModal/InvoiceModal.js
src/components/PublicationRequestSections/Charges/Charges.js
src/routes/ChargeCreateRoute/ChargeCreateRoute.js
src/routes/ChargeEditRoute/ChargeEditRoute.js

Specified currency in charge and invoice is now assigned to amount.baseCurrency and tenant currency is now assigned to localAmount.baseCurrency, invoice/line cards also reflect this change
Refactored InvoiceModal to use FormModal from stripes-kint-components
UIOA-96

refactor: Exchange rate and InvoiceModal

---

src/settings/settingsComponents/PickListValues.js

Added onClose to pickList settings page to avoid crash on dismiss pane

fix: Pick list settings

---

src/components/Modals/InvoiceModal/InvoiceModal.js

Fix so that invoiceModal no longer retains information about previous invoice after submit

fix: InvoiceModal

---

src/components/Modals/InvoiceModal/InvoiceModal.js
src/components/Modals/JournalModal/JournalModal.js
src/components/Modals/PartyModal/PartyModal.js

Refactored invoice, party and journal modals to use FormModal

refactor: Refactored modals

---

package.json
src/components/Modals/JournalModal/JournalModal.js
src/components/Modals/PartyModal/PartyModal.js
src/routes/PartyCreateRoute/PartyCreateRoute.js
src/routes/PartyEditRoute/PartyEditRoute.js
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/util/getPartyErrorMessage.js
translations/ui-oa/en.json

Upon attempting to create a joural with an already existing identifier, an error message banner is displayed, this is generic for the time beiing and will be updated upon changes to server error response mesages
Additionally fixed various bugs with journal form resetting upon error
UIOA-86

feat: Journal creation error handling

---

src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.js
src/components/InvoiceSections/InvoiceInfo/InvoiceInfo.js
src/hooks/invoiceHooks.js

Fixed an issue in which selecting another invoice would not change the invoice lines to the ones associated with the newly selected invoice
Also fixed an issue in which the batch group/vendor would not change when selecting a new invoice
UIOA-99

fix: Invoice lines refetch

---

src/routes/ChargeCreateRoute/ChargeCreateRoute.js

Set initial currency for charge create to the tenant currency
UIOA-100

feat: Charge initial currency

---

src/components/PartyFormSections/StreetAddress/StreetAddress.js

Added street addreses label to party form for use when multiple street addresses are supported

feat: Street addresses label

---

src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray/ExternalRequestIdFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray/FundingFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/IdentifiersFieldArray/IdentifiersFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/PublicationStatusFieldArray/PublicationStatusFieldArray.js

Added required validators to field array fields, this is under the assumption that a user would add to the field array and submit as an empty field, additionally this also solves the issue of the field arrays not allowing empty fields to be edited

feat: Required Field Arrays

---

package.json

Bumped sripes-kint-components to version 2.4.0

chore: Stripes k-int components bump

---

src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.test.js

Removed title select field and replaced with a text field and max character length to remove reliance on hard coded values.

feat: Party title tweak

---

src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js

Party and journal querytypedown now sort their listed results by family name and title respectively
UIOA-103

feat: QueryTypedown sort

---

src/components/InvoiceSections/InvoiceInfo/InvoiceInfo.js
src/components/PartySections/PartyInfo/PartyInfo.js
src/components/PublicationRequestFormSections/FieldArrays/PublicationStatusFieldArray/PublicationStatusFieldArray.js
src/components/PublicationRequestFormSections/LinkAgreementForm/LinkAgreementForm.js
src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
src/components/PublicationRequestSections/Funding/Funding.js
src/components/PublicationRequestSections/Publication/Publication.js
src/components/PublicationRequestSections/PublicationStatus/PublicationStatus.js
src/components/PublicationRequestSections/PublicationType/BookDetails/BookDetails.js
src/components/PublicationRequestSections/PublicationType/JournalDetails/JournalDetails.js
src/components/views/PartyForm/PartyForm.js
src/components/views/PartyForm/PartyForm.test.js
src/constants/config.js
translations/ui-oa/en.json
translations/ui-oa/en_US.json

Various QA changes made from this document:
https://docs.google.com/document/d/1EhJ1Nvk84-MfU2_iS4lV--rDcm8b93cSdKJfEW36MOM/edit?usp=sharing

feat: QA Doc tweaks

---

src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.css
src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.js
src/components/InvoiceFormSections/InvoiceTypedownForm/InvoiceTypedownForm.css
src/components/InvoiceFormSections/InvoiceTypedownForm/InvoiceTypedownForm.js
src/components/JournalFormSections/FieldArrays/InstancesFieldArray/InstancesFieldArray.js
src/components/Modals/InvoiceLineModal/InvoiceLineModal.js
src/components/PartyFormSections/StreetAddress/StreetAddress.js
src/components/PartyFormSections/StreetAddressesFieldArray/StreetAddressesFieldArray.js
src/components/PartySections/PartyInfo/PartyInfo.js
src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
src/components/PublicationRequestSections/Agreement/Agreement.js
src/components/views/ChargeView/ChargeView.js
translations/ui-oa/en.json

When an invoice has been selected, the invoice line modal upon the user attempting to create a new invoice line checks that the currency from the charge and invoice match and if not a warning is displayed
UIOA-109

feat: Charge/Invoice currency warning

---

src/util/publicationRequestSubmitHandler.js

Fixed an issue in which OA/DOAJ status within the publication request was not updated if the value was removed

fix: DOAJ/OA Status fix

---

src/components/Modals/InvoiceLineModal/InvoiceLineModal.js
src/components/views/ChargeView/ChargeView.js
translations/ui-oa/en.json

Tweaked invoice line modal to display information that is displayed within the invoice line card for consistency

feat: Invoice lines modal tweaks

---

src/components/views/CorrespondenceView/CorrespondenceView.js
src/index.js

Changed correspondence view to be a third view pane instead of a standalone full page, inline with the charge view model

feat: Correspondence view pane

---

src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js

Fixed the party typedown bug in which the query typedown was not being corrrectly recognised by screenreaders

fix: QueryTypedown aria-label

---

src/routes/JournalsRoute/JournalsRoute.js
src/routes/PartiesRoute/PartiesRoute.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Publication requests, people and journals are now sorted by request number, famil/given names and title respectively, this is in preperation for allowing the users to sort the MCLs by clicking the headers

feat: SASQ Sorting

---

src/components/CorrespondenceFormSections/CorrespondenceInfoForm/CorrespondenceInfoForm.js
src/components/JournalFormSections/FieldArrays/InstanceIdentifiersFieldArray/InstanceIdentifiersFieldArray.js
src/components/JournalFormSections/JournalInfoForm/JournalInfoForm.js
src/components/PartyFormSections/OtherEmailsFieldArray/OtherEmailsFieldArray.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js
src/components/PartyFormSections/StreetAddress/StreetAddress.js

Added character limits to various other fields within OA, namely correspondence, charge, party and journal forms

feat: Additional field limits

---

src/components/InvoiceFormSections/CreateInvoiceForm/CreateInvoiceForm.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Made numerous minor tweaks based on the OA QA document

feat: Minor QA tweaks

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js
src/util/validators.js
translations/ui-oa/en.json

Added validation to publication URL field within publication request
UIOA-112

feat: URL Validation

---

package.json
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js

Added the final form focus dependancy to enable the use of decorators within the form component which correctly focus upon errors upon attempted submission
UIOA-112

feat: Form focus on error 

---

src/components/JournalFormSections/JournalStatusForm/JournalStatusForm.js
src/components/JournalFormSections/JournalStatusForm/index.js
src/components/JournalFormSections/index.js
src/components/views/Journal/Journal.js
src/components/views/JournalForm/JournalForm.js
src/components/views/JournalForm/index.js
src/index.js
src/routes/JournalEditRoute/JournalEditRoute.js
src/routes/JournalEditRoute/index.js
src/routes/index.js
src/util/urls.js
translations/ui-oa/en.json

Added the ability for the user to edit the DOAJ/OA status of a given work, this sets up for the editing of journals in the future however it is currently constrained to these two fields. This may require refactoring in the future as we use essentially the same form view for all section within OA
UIOA-119

feat: Journal status edit

---

src/components/Modals/InvoiceLineModal/InvoiceLineModal.js
src/components/Modals/InvoiceModal/InvoiceModal.js
src/components/Modals/JournalModal/JournalModal.js
src/components/Modals/PartyModal/PartyModal.js
src/components/views/ChargeForm/ChargeForm.js
src/components/views/CorrespondenceForm/CorrespondenceForm.js
src/components/views/JournalForm/JournalForm.js
src/components/views/LinkInvoiceForm/LinkInvoiceForm.js
src/components/views/PartyForm/PartyForm.js
src/components/views/PublicationRequestForm/PublicationRequestForm.js
src/routes/ChargeCreateRoute/ChargeCreateRoute.js
src/routes/ChargeEditRoute/ChargeEditRoute.js
src/routes/CorrespondenceCreateRoute/CorrespondenceCreateRoute.js
src/routes/CorrespondenceEditRoute/CorrespondenceEditRoute.js
src/routes/JournalEditRoute/JournalEditRoute.js
src/routes/LinkInvoiceRoute/LinkInvoiceRoute.js
src/routes/PartyCreateRoute/PartyCreateRoute.js
src/routes/PartyEditRoute/PartyEditRoute.js
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js

Added async await to all forms within OA to enable use of submitting value from within the form state

refactor: Async submit handlers

---

src/components/JournalSections/JournalInstances/JournalInstances.js
src/components/JournalSections/JournalInstances/JournalInstances.test.js

Tweaked journal view to have enlarged journal title, display OA/DOAJ status and correctly display rules between each instance

feat: Journal view tweaks

---

src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Added the ability for the user to search publication requests by external request ids
UIOA-124

feat: Request external ID search

---

src/routes/CorrespondenceEditRoute/CorrespondenceEditRoute.js
src/routes/PartyEditRoute/PartyEditRoute.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js

Fixed an issue in which upon submitting a form, the old values of the edited form would display before the form was closed
Fixed an issue in which the old form values would be retrieved from the cache upon the editing of a form

fix: Form initial values

---

src/settings/settingsComponents/PickListValues.js
translations/ui-oa/en.json

Added labels and translation to various elements of the picklist values within settings
UIOA-127

feat: Picklist values labels

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/components/ChargeFormSections/PayersFieldArray/PayersFieldArray.js
src/components/ChargeSections/Payers/Payers.js
src/routes/ChargeEditRoute/ChargeEditRoute.js

Changed all remaining instances of formatted number to instead display the 3 letter notation followed by the amount
UIOA-139

refactor: Currency format

---

src/components/ChargeSections/Payers/Payers.js

Updated translation for payers "is empty" message

chore: Translations

---

src/constants/endpoints.js
src/hooks/useChecklistItemDefinitions.js
src/hooks/useMutateChecklistItemDefinitions.js
src/settings/index.js
src/settings/settingsComponents/ChecklistItemDefinitions.js
src/settings/settingsComponents/index.js
translations/ui-oa/en.json

Added a settings page where one can add ChecklistItems
UIOA-142

feat: ChecklistItems

---

src/settings/settingsComponents/ChecklistItemDefinitions.js

Added weight default to checklistItemDefinition ActionList (Will take effect when kint-comps 2.8.0 is released)

feat: checklist item definition defaults

---

src/components/JournalFormSections/JournalStatusForm/JournalStatusForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
src/components/PublicationRequestSections/Publication/Publication.js
src/components/PublicationRequestSections/PublicationType/JournalDetails/JournalDetails.js
src/components/PublicationRequestSections/PublicationType/JournalDetails/JournalDetails.test.js
src/components/views/JournalForm/JournalForm.js
src/util/journalUtils.js
translations/ui-oa/en.json
translations/ui-oa/en_US.json

When editing a journal the information is now displayed alongside the editable fields
UIOA-145

feat: Journal information display

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js
src/util/filterSelectValues.js

Changed publisher select field to selection component for filtering of larger data sets
UIOA-147

feat: Publisher selection

---

src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/Checklist/ChecklistNotes/ChecklistNotes.js

Adjusted note TextArea field to align with character limit
Added a conditional for the Infopopover not displaying if the checklist item does not have an assigned description

feat: Checklist tweaks

---

jest.config.js
test/jest/resolver.js

Updated jest.config to include resolver

test: Updated jest config

---

src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray/ExternalRequestIdFieldArray.js
src/components/PublicationRequestSections/Charges/Charges.js

Upon creating/editing a publication request focus is automatically applied to the external request Id button

feat: External request id focus

---

src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.js
src/components/InvoiceFormSections/InvoiceTypedownForm/InvoiceTypedownForm.js
src/components/JournalSections/JournalInstances/JournalInstances.js
src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js

Added IDs to all QueryTypedowns
Updated id for hide/show tooltip to be unique between all items
Updated ids for checklist icon slect options to correctly reflect option functions
Added tabIndex attribute to the surrounding div of the jounral instances to allow for it to be focused
UIOA-154

fix: WCAG Changes

---

CHANGELOG.md
README.md

Updated README to include installation documentation and prerequisites along with an updated introduction, additionally updated CHANGELOG to reflect changes made within version 1.0
[UIOA-156](https://issues.folio.org/browse/UIOA-156)

docs: Updated README/CHANGELOG

---

package.json

Updated organizations okapi interface and added finance.exchange-rate

chore: Updated Okapi interfaces

---

translations/ui-oa/en.json

Added missing translations for pick list values EditableRefdataList
[UIOA-178](https://issues.folio.org/browse/UIOA-178)

fix: Pick list values translations

---

package.json

Changes finance exchange rate okapi version

fix: Finance okapi

---

src/settings/index.js

Removed hasPerm conditional for deprecated picklist permissions
[UIOA-181](https://issues.folio.org/browse/UIOA-181)

fix: Picklist permissions

---

src/components/Checklist/Checklist.css
src/components/Checklist/Checklist.js
src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/Checklist/ChecklistNotes/ChecklistNotes.js
src/components/Checklist/ChecklistNotes/ChecklistNotesModal.js
src/components/views/Party/Party.js
src/components/views/PublicationRequest/PublicationRequest.js
src/settings/settingsComponents/ChecklistItemDefinitions/index.js
src/settings/settingsComponents/index.js
translations/ui-oa/en.json

Fixed accessibility issues within checklist component

fix: Accessibility tweaks

---

translations/ui-oa/en.json

Added translations for CustomPropertiesCard used within agreement view component

chore: Custom properties translations

---

src/components/Modals/ReportingModal/ReportingModal.js
src/components/ReportingFormSections/ReportingInfoForm/ReportingInfoForm.js

Added support for reporting to have multiple institution names available. Field is disabled when only one option is available and enabled when multiple are available
[UIOA-185](https://issues.folio.org/browse/UIOA-185)

feat: Multiple institution names

---

src/constants/panesetConfigs.js
src/routes/JournalsRoute/JournalsRoute.js
src/routes/PartiesRoute/PartiesRoute.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Panesets are now properly seristent between routes

feat: Paneset

---

src/components/Checklist/Checklist.js

Fixed loading pane import from erm-components to stripes-components

fix: Loading pane import fix

---

src/components/views/Journal/Journal.js
src/components/views/Party/Party.js
src/components/views/PublicationRequest/PublicationRequest.js

Fixed issue in which edit button for publication requests, parties and works did not render

fix: Edit button perms

---

src/settings/settingsComponents/ChecklistItemDefinitions/ChecklistItemDefinitionForm.js
src/util/validators.js
translations/ui-oa/en.json

Added validation to checklist item definition label field

feat: Checklist item definition validation

---

src/components/SearchAndFilter/PartiesFilters/PartiesFilters.js
src/components/SearchAndFilter/PublicationRequestsFilters/PublicationRequestsFilters.js

Fixed ariaLbaelledBy props for publication request filters and parties filters
[UIOA-188](https://issues.folio.org/browse/UIOA-188)

fix: Multiselect ariaLabelledBy

---

src/components/SearchAndFilter/ChecklistFilter/ChecklistFilter.js

Fixed an issue in which queries were not correctly being generated due to incorrect grouping

fix: Filter strings grouping

---

src/components/SearchAndFilter/ChecklistFilter/ChecklistFilterRule.js
translations/ui-oa/en.json

Added missing translations for checklist filter attributes, operators and values

feat: Checklist filter translations

---

package.json

Added additional potential version to stripes-erm-components using OR operator

chore: Stripes-erm-components multiple versions

---

src/components/PublicationRequestFormSections/RequestInfoForm/RequestInfoForm.js
test/resources/refdata.js

Fixed closureReason ref data values from "PublicationRequest.RejectionReason" to PublicationRequest.ClosureReason"
[UIOA-194](https://issues.folio.org/browse/UIOA-194)

fix: Closure reason refdata

---

src/components/ReportingFormSections/ReportingAgreementForm/ReportingAgreementForm.js

Fixed conditional validation on payment period and publication status fields within the transformative agreement report format
[UIOA-192](https://issues.folio.org/browse/UIOA-192)

fix: Agreement report conditional validation

---

src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js

Fixed an issue in which istitution lvel fields within the publication request were not being automatically populated with values from the selected party
[UIOA-199](https://issues.folio.org/browse/UIOA-199)

fix: Institution levels population

---

src/components/Modals/ReportingModal/ReportingModal.js
translations/ui-oa/en.json
translations/ui-oa/en_US.json

Updated the creation callout upon report genration to display the filename of the report

feat: Report filename callout

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

Removed bigtest actions from build-npm yaml files

chore: Bigtest removal

---

CHANGELOG.md
package.json

And upgrade `stripes-acq-components` to `v4`

UIOA-204 Remove unneeded react-redux ref

---

CHANGELOG.md
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js

Added the ability for the journal typedown to be searched by matching ISSNs
[UIOA-210](https://issues.folio.org/browse/UIOA-210)

feat: Journal typedown ISSN search

---

CHANGELOG.md
package.json

Bumped stripes kint components dependency to 4.4.0

chore: Stripes-kint-components bump

---

CHANGELOG.md

Updated changelog for changes from UIOA-211

docs: Updated CHANGELOG

---

src/components/JournalFormSections/FieldArrays/InstancesFieldArray/InstancesFieldArray.js
src/components/Modals/InvoiceModal/InvoiceModal.js

chore: Cyclic imports

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js

Tweaked styling for journal QueryTypedown

style: Journal QueryTypedown styling

---

CHANGELOG.md

Updated CHANGELOG, ensured dependencies are up to date
UIOA-214

chore: Release 1.1.0

---

package.json

Changed OA interface for grails 5 changes to mod-oa

feat: Grails 5

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/routes/ChargeCreateRoute/ChargeCreateRoute.js

Fixed discount type id for charge creation form to correctly use traslations when pick list value has been changed
[UIOA-219](https://issues.folio.org/browse/UIOA-219)

fix: Charge discount type id

---

CHANGELOG.md

Updated changelong after 2.0.1 release

chore: Post release

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json
src/components/ChargeFormSections/PayersFieldArray/PayersFieldArray.js
src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/Checklist/ChecklistNotes/ChecklistNotes.js
src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
src/components/PublicationRequestSections/Charges/Charges.js
src/components/PublicationRequestSections/Correspondence/Correspondence.js
src/components/views/CorrespondenceView/CorrespondenceView.js
src/components/views/Journal/Journal.js
src/components/views/Party/Party.js
src/components/views/PublicationRequest/PublicationRequest.js
src/routes/JournalsRoute/JournalsRoute.js
src/routes/PartiesRoute/PartiesRoute.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Updated CHANGELOG.md and bumped version to 2.0.2
* UIOA-229 UI uses non-existent permission oa.work.manage
* Payers' amounts lose decimal separator with non-English locale
refs UIOA-231

chore: Release 2.0.2

---

package.json

As per UIOA-233: Introducing new `charge` permissions, and some permission renaming for consistency

UIOA-233: Updated permissions

---

GUIDANCE.md
LICENSE

Updated license and andded guidance.md file

UIOA-241: Update module license and guidance

---

CHANGELOG.md
GUIDANCE.md
LICENSE
package.json

Added new CHANGELOG section and bumped app version number to 2.2.0
UIOA-225

chore: Post release 2.1.0

---

CHANGELOG.md
package.json

Added changelog section and bumped version to 2.3.0

chore: Post-release 2.2.0

---

CHANGELOG.md
package.json

Bumped version to 3.1.0, added new CHANGELOG.md section

chore: Post release 3.0.0
