folio-org/ui-oa

CHANGELOG.md
package.json

Upgrade `@folio/react-intl-safe-html` for compatibility with
`@folio/stripes` `v7` (react 17, react-intl 5).
@SamHepburnKI, @EthanFreestone: I don't have write privs in this repo to add PR reviewers. If this looks good to you, please merge it. Thanks!
Refs [UIOA-25](https://issues.folio.org/browse/UIOA-25), [STRIPES-769](https://issues.folio.org/browse/STRIPES-769)

UIOA-25 upgrade react-intl-safe-html

---

src/components/PublicationRequestFormSections/PublicationForm.js

The switch from using refdfataValue.value to refdataValue.id caused some logic that was reading the form value to no longer match. Introduced a function to fetch an id from a desc/value pair, and matched the form values against those to restore functionality
UIOA-43

fix: Form elements not showing up

---

src/components/PublicationRequestSections/PublicationStatus/PublicationStatus.js

Status date now displays YYY-MM-DD instead of YYY-MM-DDT00:00Z
UI-OA 48

fix: Formatted 'Status Date' field

---

src/components/PublicationRequestFormSections/LinkAgreementForm/LinkAgreementForm.js

"Without agreement" is now a field on the PublicationRequest, wired up checkbox to work as expected
MODOA-7

chore: no agreement checkbox wired up

---

src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Publication requests MCL now correctly displays requests corresponding author name

fix: PublicationRequests corresponding author name

---

src/components/PublicationRequestSections/Agreement/Agreement.js

Custom props no longer rendered when agreement contains no custom props

fix: Custom Properties Conditional

---

src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.js
translations/ui-oa/en.json

Invoice line generation is now disabled for invoices which have the status of Approved, Paid or cancelled, a warning banner is also now displayed to reflect this

feat: Invoice tweaks

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/components/ChargeSections/ChargeInfo/ChargeInfo.js
src/components/CorrespondenceFormSections/CorrespondenceInfoForm/CorrespondenceInfoForm.js
src/components/PartyFormSections/OtherEmailsFieldArray/OtherEmailsFieldArray.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js
src/components/PartyFormSections/StreetAddress/StreetAddress.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js
src/routes/CorrespondenceEditRoute/CorrespondenceEditRoute.js
src/util/publicationRequestSubmitHandler.js
translations/ui-oa/en.json

Fixed issue in which fields would not be saved if empty upon submission whilst editing, this has been fixed in correspondence, charges, publication requests and party edit forms.
Note: publicationSubmitHandler may require some refactoring due to the amount of select fields within the publication request edit form. Also need a decision on whether the field arrays fields should be required, is there a scenario in which users would be submitting the field arrays with empty fields and not simply deleting excess fields.

fix: Empty field parsing

---

src/components/InvoiceFormSections/InvoiceLineTypedownForm/InvoiceLineTypedownForm.js
src/components/InvoiceFormSections/InvoiceTypedownForm/InvoiceTypedownForm.js
src/components/PublicationRequestFormSections/PartyTypedownForm/PartyTypedownForm.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationJournal/PublicationJournal.js
src/constants/config.js

Querytypedown list items now highlight the items which match the input typed by the user, may require changes to remove the hightlight after the item has been selected
Also tweaked default pane width from 25% to 35%, may change based on feedback

feat: Typedown highlight

---

src/util/useOARefdata.js

Ref data is now sorted after fetch for consistency within OA, i.e all ref data values are displayed the same way everytime upon rendering of a page, this was especially evident with the discount type within the charge edit page

feat: Reference data sort

---

src/components/PublicationRequestSections/Charges/Charges.js
translations/ui-oa/en.json
translations/ui-oa/en_US.json

Now using react-intl tooling for currency symbol handling
Added a link to charge status within description column which links to related invoice line
Changed "Estimated price" column to "Estimated prices inc. tax and discounts"
Estimated prices column no longer displays the specified conversion if the local and specified currency are the same
Charges MCL are now sortable and can now are sorted by default
UIOA-106

feat: Charge MCL tweaks

---

src/components/Modals/InvoiceLineModal/InvoiceLineModal.js
src/components/views/ChargeForm/ChargeForm.js
src/components/views/ChargeForm/ChargeForm.test.js
src/components/views/CorrespondenceForm/CorrespondenceForm.js
src/components/views/CorrespondenceForm/CorrespondenceForm.test.js
src/components/views/CorrespondenceView/CorrespondenceView.test.js
src/components/views/LinkInvoiceForm/LinkInvoiceForm.js
src/components/views/PartyForm/PartyForm.js
src/components/views/PartyForm/PartyForm.test.js
src/components/views/PublicationRequestForm/PublicationRequestForm.js
src/routes/ChargeCreateRoute/ChargeCreateRoute.js
src/routes/ChargeEditRoute/ChargeEditRoute.js
src/routes/CorrespondenceCreateRoute/CorrespondenceCreateRoute.js
src/routes/CorrespondenceEditRoute/CorrespondenceEditRoute.js
src/routes/LinkInvoiceRoute/LinkInvoiceRoute.js
src/routes/PartyCreateRoute/PartyCreateRoute.js
src/routes/PartyEditRoute/PartyEditRoute.js
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js

Fixed an issue within OA in which a forms "submit" button wasn't disabled whilst the form was being submitted, allowing the users to make multiple copies of the same record by repeatedly clicking the "submit" button, unfortunately the submitting form state prop wasn't working as intended, so I utilised the isLoading prop from the react query to handle this.

fix: Form multiple submit

---

src/components/PublicationRequestSections/Funding/Funding.js
src/components/PublicationRequestSections/Publication/Publication.js
src/components/PublicationRequestSections/PublicationStatus/PublicationStatus.js
src/components/PublicationRequestSections/RequestInfo/RequestInfo.js

Repeatable values within the publication request view panes are now sorted upon render, the MCLs are not sorted as this is purely more for consistency, the fields are external request ids, publication requests, identifiers and fundings

feat: Publication request values sort

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js
src/components/PublicationRequestSections/Charges/Charges.js
src/components/PublicationRequestSections/Correspondence/Correspondence.js
src/components/PublicationRequestSections/Correspondence/Correspondence.test.js
src/components/PublicationRequestSections/Funding/Funding.js
src/components/PublicationRequestSections/Funding/Funding.test.js
src/components/PublicationRequestSections/Publication/Publication.js
src/components/PublicationRequestSections/Publication/Publication.test.js
src/components/PublicationRequestSections/PublicationStatus/PublicationStatus.js
src/components/PublicationRequestSections/PublicationStatus/PublicationStatus.test.js
src/components/PublicationRequestSections/RequestInfo/RequestInfo.js
src/components/PublicationRequestSections/RequestInfo/RequestInfo.test.js
translations/ui-oa/en.json

Tweaked various areas of the publication request view to display custom messages for charges, correspondence publication statuses and fundings when non have been provided, and also to hide the external request ids and  identifiers when non have been provided

feat: Empty sections tweaks

---

src/components/PublicationRequestFormSections/PublicationForm/PublicationBook/PublicationBook.js
src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js
src/components/PublicationRequestSections/PublicationType/BookDetails/BookDetails.js
src/routes/PublicationRequestCreateRoute/PublicationRequestCreateRoute.js
src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js
src/util/getRDVId.js
src/util/publicationRequestSubmitHandler.js

Fixed an issue in which both work and book information would be saved if the user filled fields for one publication type and then changed the publication type, the publication request submit handler now removed the opposing publication types fields from the submit values. This may require a bit more QA as there was a significant amount of refactoring within the publicationRequestSubmitHandler 
UIOA-108

fix: Publication type change

---

src/components/PublicationRequestSections/PublicationType/BookDetails/BookDetails.js

Fixed an issue in which an error would occur when a user attempted to access a publication request which had the publication type "book" but didnt have a year of publication saved

fix: Book year error

---

src/components/JournalFormSections/FieldArrays/InstanceIdentifiersFieldArray/InstanceIdentifiersFieldArray.js
src/components/PartyFormSections/OtherEmailsFieldArray/OtherEmailsFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/ExternalRequestIdFieldArray/ExternalRequestIdFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/FundingFieldArray/FundingFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/IdentifiersFieldArray/IdentifiersFieldArray.js
src/components/PublicationRequestFormSections/FieldArrays/PublicationStatusFieldArray/PublicationStatusFieldArray.js

Fixed an issue in which validation errors would cause alignment issues within the field arrays, fixed by removed the flexbox "middle" prop and by manually adjusting the css of the trash icons within each field array "padding-top: 25px"

fix: Field array alignment

---

src/routes/PublicationRequestEditRoute/PublicationRequestEditRoute.js

Repeatable fields within the publication requests are now consistently sorted when editing a request this includes external ids, fundings , publication statuses and identifiers
UIOA-102

feat: Field array sort

---

src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Fixed an issue in which the corresponding authro column of the requests MCL was interactable but wasnt sorting upon click
UIOA-111

fix: Corresponding author sort

---

src/components/PublicationRequestFormSections/LinkAgreementForm/LinkAgreementForm.js
src/components/PublicationRequestSections/Charges/Charges.js
translations/ui-oa/en.json

Added an error message which is displayed when the agreements handler is not working as intended, this removed the original text field which was used as a replacement

feat: Agreements error message

---

package.json

Bumped the handler stripes  registry dependency to 1.1.1 in an attempt to fix the issue with the LookUp component not working correctly

chore: Handler stripes registry bump

---

src/components/JournalFormSections/FieldArrays/InstancesFieldArray/InstancesFieldArray.js

Fixed the instance subtype value from being saved as the id , now correctly saves as either print or electronic

fix: Instance subtype value

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js
src/components/ChargeFormSections/PayersFieldArray/PayersFieldArray.css
src/components/ChargeFormSections/PayersFieldArray/PayersFieldArray.js
src/util/getEstimatedInvoicePrice.js
src/util/validators.js
translations/ui-oa/en.json

Added remaining amount value to payers accordion to allow for tracking of the total of amounts entered so far
Added validation so that the user cannot enter a payers total greater than that of the charge total
Added validation on payer amount field to ensure positive and limited value
UIOA-122

feat: Multiple payers tweaks

---

src/components/PublicationRequestSections/Charges/Charges.css
src/components/PublicationRequestSections/Charges/Charges.js
translations/ui-oa/en.json

Changes translations and layouts of the request charges MCL
MCL now displays net amount, calculated amount and invoice line, which provides a link to the associated invoice line or displays a warning when a charge is invoice but has not been linked
Additionally changes formatting of currency to display only the 3 letter notations for the charges MCL
UIOA-138

feat: Charges MCL tweaks

---

src/components/PublicationRequestFormSections/LinkAgreementForm/LinkAgreementForm.js

Tweaked the agreement lookup component rendering so that if the request is without an agreement then nothing is rendered, but if an agreement can be linked but the lookup component isnt functioning, then it renders the error message

fix: Agreement link fix

---

src/components/PublicationRequestSections/Publication/Publication.js

Tweaked publication accordion information to display DOI/Local reference and DOAJ/OA status on two seperate rows, due to potential wrapping of longer DOIs

feat: Publication tweaks

---

package.json

stripes-erm-components must be included under peerDependencies instead of dependencies if it is provided as a direct-dep by the platform.
UIOA-148

chore: Added stripes-erm-components to peer dependencies

---

src/components/Checklist/ChecklistNotes/ChecklistNotes.js

Aligned edit/trash icons to right side of notes modal
Tweaked save/cancel button styling to have them be right aligned like the edit/trash icons, aditionally removed conditional rendering of cancel button and replaced with disable prop

style: Checklist notes

---

package.json

Fixing a previous commit in which stripes-erm-components should have been in peer dependencies instead of both
[UIOA-148](https://issues.folio.org/browse/UIOA-148)

UIOA-148: Removed stripes-erm-components from dependencies

---

src/components/Checklist/Checklist.js
src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/Checklist/ChecklistNotes/ChecklistNotes.js
src/components/Checklist/ChecklistNotes/ChecklistNotesModal.js
translations/ui-oa/en.json

Fixed cancel button conditional in which it would be disabled even when other notes existed within the modal
Fixed a bug in which creating a new note within an unedited checklist item would result in the note not correctly rendering
Styled not buttons correctly so that large blocks of text for note would not disrupt styling of edit/trash buttons

fix: Checklist

---

src/components/ChargeSections/ChargeBreakdown/ChargeBreakdown.js

Remove the clickable row action from the "Charge breakdown" MCL
UIOA-173

fix: Charge breakdown MCL

---

package.json

Bumped stripes kint components dependency to 3.0.4

chore: Stripes-kint-components bump

---

src/components/Modals/ReportingModal/ReportingModal.js
src/components/ReportingFormSections/ReportingInfoForm/ReportingInfoForm.js

Added support so that multiple charge categories/statuses can be added to the query parameters, additionally added conditionals so that if no payment period, charge categories or statuses are supplied, they will not be included in query parameters
[UIOA-131](https://issues.folio.org/browse/UIOA-131)

feat: Multiple/Null report parameters

---

translations/ui-oa/en.json
translations/ui-oa/en_US.json

Changed all associated OA titles to sentence case, from "Open Access" to "Open access"
[UIOA-180](https://issues.folio.org/browse/UIOA-180)

fix: Sentence case title

---

package.json

To allow the user to access the relevant refdata, oa.refdata.read  permission is now included in the  ui-oa.oa.manage and ui-oa.oa.view permission sets
[UIOA-183](https://issues.folio.org/browse/UIOA-183)

chore: Refdata permissions

---

src/components/Checklist/ChecklistItem/ChecklistItem.js
src/components/Checklist/ChecklistNotes/ChecklistNotes.js
src/components/views/Journal/Journal.js
src/components/views/Party/Party.js
src/components/views/Party/Party.test.js
src/components/views/PublicationRequest/PublicationRequest.js
src/routes/PublicationRequestsRoute/PublicationRequestsRoute.js

Changed Edit/New buttons for requests, parties and journals to be hidden if user does not have required permissions, additionally changed Checklist Hide/Show button and Notes to be disabled if missing perms
[UIOA-184](https://issues.folio.org/browse/UIOA-184)

feat: Edit/New records and Checklist permissions

---

package.json

kint-components 4.0.0 introduces a breaking change, encodeURI should no longer be performed on the output of generateKiwtQueryParams unless `encode` is set to false

chore: Bumped to stripes-kint-components ^4.0.0

---

src/components/Checklist/ChecklistItem/ChecklistItem.js

Added disabled prop to checklist item icon select for outcome which disables the button when the user is missing required permissions
[UIOA-184](https://issues.folio.org/browse/UIOA-184)

fix: Checklist item outcome permission

---

src/components/SearchAndFilter/ChecklistFilter/ChecklistFilter.js
translations/ui-oa/en.json

Added button to checklist filters accordion header to allow for re-application of filters upon changing of a checklist item
[UIOA-198](https://issues.folio.org/browse/UIOA-198)

feat: Reapply checklist filters button

---

CHANGELOG.md
src/components/PartyFormSections/OtherEmailsFieldArray/OtherEmailsFieldArray.js
src/components/PartyFormSections/PartyInfoForm/PartyInfoForm.js

Updated max length props for mainEmail and alternateEmails from 36 characters to 255 to reflect data type
[UIOA-205](https://issues.folio.org/browse/UIOA-205), [UIOA-206](https://issues.folio.org/browse/UIOA-206)

fix: Email fields max length

---

CHANGELOG.md
src/components/PublicationRequestFormSections/PublicationForm/PublicationForm/PublicationForm.js

Modified publication title fields maxLength prop to 4096 to be able to accommodate longer titles
[UIOA-212](https://issues.folio.org/browse/UIOA-212)

fix: Publication title field max length

---

src/components/Checklist/HiddenHeader/HiddenHeader.css

Hey @Jack-Golding, I ran into this issue while working on stripes transpilation:
````css
/ui-oa/src/components/Checklist/HiddenHeader/HiddenHeader.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './@folio/stripes-components/lib/sharedStyles/interactionStyles.css' in '/projects/folio/transpilation/ui-oa/src/components/Checklist/HiddenHeader'
at /projects/folio/transpilation/node_modules/webpack/lib/Compilation.js:2016:28
at /projects/folio/transpilation/node_modules/webpack/lib/NormalModuleFactory.js:798:13
at eval (eval at create (/projects/folio/transpilation/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at …
```

Adjust path to interaction styles

---

package.json

Updated all dependencies for compatibility with react v18/stripes v9: handler-stripes-registry v2.1.0, service-interaction v2.0.0, stripes-acq-components v5.0.0,
UIOA-220

chore: Bump dependencies

---

src/components/ChargeFormSections/ChargeInfoForm/ChargeInfoForm.js

Fixed issue in which the decimal separator was ignored when saving with non-english locale
[UIOA-222](https://folio-org.atlassian.net/browse/UIOA-222)

fix: Decimal separator ignored when saving with non-english locale

---

.github/workflows/build-npm.yml
.github/workflows/stuck-license-cla.yml

Added stuck license cla button comment workflow, Prevent buildNPM Snapshot having to run twice on PRs

chore: Workflow tweaks

---

package.json

Module settings are needed by all users of the OA module so that they can be used in the module. In particular the `default_tax` appSetting is needed when creating charges
By granting `oa.settings.read` as a subpermission of `module.oa.enabled` it ensures that any user of the module can read the settings.

Granted oa.settings.read on module.oa.enabled

---

src/routes/JournalsRoute/JournalsRoute.js

We do not currently support sorting journal list by ISSN, so neither ISSN (Print) no ISSN (Electronic) columns should not appear as a sortable column in the UI

UIOA-238: Remove sort options from ISSN(Print) and ISSN(Electronic) column

---

package.json

ui-oa.view and ui-oa.edit have been replaces with ui-oa.all-open-access.view and ui-oa.all-open-access.edit, so need to update anywhere they are used in subperms

UIOA-233: Update subperm refs to ui-oa.view and edit

---

src/components/views/ChargeView/ChargeView.js
src/components/views/CorrespondenceView/CorrespondenceView.js

Updated required permissions for charge/correspondence action menu options, fixed issue in which action menu would still display if available options < 1

UIOA-242: Charge/Correspondence action menu
